/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.Bookmarks;
import jooq.tables.Events;
import jooq.tables.Hosts;
import jooq.tables.Users;
import jooq.tables.Views;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DutyIt extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>duty_it</code>
     */
    public static final DutyIt DUTY_IT = new DutyIt();

    /**
     * The table <code>duty_it.bookmarks</code>.
     */
    public final Bookmarks BOOKMARKS = Bookmarks.BOOKMARKS;

    /**
     * The table <code>duty_it.events</code>.
     */
    public final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>duty_it.hosts</code>.
     */
    public final Hosts HOSTS = Hosts.HOSTS;

    /**
     * The table <code>duty_it.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>duty_it.views</code>.
     */
    public final Views VIEWS = Views.VIEWS;

    /**
     * No further instances allowed
     */
    private DutyIt() {
        super("duty_it", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Bookmarks.BOOKMARKS,
            Events.EVENTS,
            Hosts.HOSTS,
            Users.USERS,
            Views.VIEWS
        );
    }
}
