/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Bookmarks;
import jooq.tables.Events;
import jooq.tables.Hosts;
import jooq.tables.Users;
import jooq.tables.Views;


/**
 * Convenience access to all tables in duty_it.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>duty_it.bookmarks</code>.
     */
    public static final Bookmarks BOOKMARKS = Bookmarks.BOOKMARKS;

    /**
     * The table <code>duty_it.events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>duty_it.hosts</code>.
     */
    public static final Hosts HOSTS = Hosts.HOSTS;

    /**
     * The table <code>duty_it.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>duty_it.views</code>.
     */
    public static final Views VIEWS = Views.VIEWS;
}
