# Local Development Profile (H2 Database)
spring:
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:file:./data/duit;MODE=MySQL;AUTO_SERVER=TRUE
    #    username: sa
    #    password:

    # local mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${LOCAL_DB_PORT}/${DB_NAME}?rewriteBatchedStatements=true&allowLoadLocalInfile=true&useServerPrepStmts=false&cachePrepStmts=true&prepStmtCacheSize=500&prepStmtCacheSqlLimit=2048
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 300000
      connection-timeout: 3000

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 업데이트 (데이터 유지)
    show-sql: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 3000

# 파일 스토리지 설정 (로컬)
file:
  upload-dir: C:/temp/duit-uploads
  base-url: http://localhost:8080
