/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmarks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Boolean isAddedToCalendar;
    private Long eventId;
    private Long id;
    private Long userId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Bookmarks() {}

    public Bookmarks(Bookmarks value) {
        this.isAddedToCalendar = value.isAddedToCalendar;
        this.eventId = value.eventId;
        this.id = value.id;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Bookmarks(
        Boolean isAddedToCalendar,
        Long eventId,
        Long id,
        Long userId,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.isAddedToCalendar = isAddedToCalendar;
        this.eventId = eventId;
        this.id = id;
        this.userId = userId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>duty_it.bookmarks.is_added_to_calendar</code>.
     */
    public Boolean getIsAddedToCalendar() {
        return this.isAddedToCalendar;
    }

    /**
     * Setter for <code>duty_it.bookmarks.is_added_to_calendar</code>.
     */
    public Bookmarks setIsAddedToCalendar(Boolean isAddedToCalendar) {
        this.isAddedToCalendar = isAddedToCalendar;
        return this;
    }

    /**
     * Getter for <code>duty_it.bookmarks.event_id</code>.
     */
    public Long getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>duty_it.bookmarks.event_id</code>.
     */
    public Bookmarks setEventId(Long eventId) {
        this.eventId = eventId;
        return this;
    }

    /**
     * Getter for <code>duty_it.bookmarks.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>duty_it.bookmarks.id</code>.
     */
    public Bookmarks setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>duty_it.bookmarks.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>duty_it.bookmarks.user_id</code>.
     */
    public Bookmarks setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>duty_it.bookmarks.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>duty_it.bookmarks.created_at</code>.
     */
    public Bookmarks setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>duty_it.bookmarks.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>duty_it.bookmarks.updated_at</code>.
     */
    public Bookmarks setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Bookmarks other = (Bookmarks) obj;
        if (this.isAddedToCalendar == null) {
            if (other.isAddedToCalendar != null)
                return false;
        }
        else if (!this.isAddedToCalendar.equals(other.isAddedToCalendar))
            return false;
        if (this.eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!this.eventId.equals(other.eventId))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.isAddedToCalendar == null) ? 0 : this.isAddedToCalendar.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Bookmarks (");

        sb.append(isAddedToCalendar);
        sb.append(", ").append(eventId);
        sb.append(", ").append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
