/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Boolean autoAddBookmarkToCalendar;
    private Boolean bookmark;
    private Boolean calendar;
    private Boolean marketing;
    private Byte providerType;
    private Boolean push;
    private LocalDateTime createdAt;
    private Long id;
    private LocalDateTime updatedAt;
    private String deviceToken;
    private String email;
    private String nickname;
    private String providerId;

    public Users() {}

    public Users(Users value) {
        this.autoAddBookmarkToCalendar = value.autoAddBookmarkToCalendar;
        this.bookmark = value.bookmark;
        this.calendar = value.calendar;
        this.marketing = value.marketing;
        this.providerType = value.providerType;
        this.push = value.push;
        this.createdAt = value.createdAt;
        this.id = value.id;
        this.updatedAt = value.updatedAt;
        this.deviceToken = value.deviceToken;
        this.email = value.email;
        this.nickname = value.nickname;
        this.providerId = value.providerId;
    }

    public Users(
        Boolean autoAddBookmarkToCalendar,
        Boolean bookmark,
        Boolean calendar,
        Boolean marketing,
        Byte providerType,
        Boolean push,
        LocalDateTime createdAt,
        Long id,
        LocalDateTime updatedAt,
        String deviceToken,
        String email,
        String nickname,
        String providerId
    ) {
        this.autoAddBookmarkToCalendar = autoAddBookmarkToCalendar;
        this.bookmark = bookmark;
        this.calendar = calendar;
        this.marketing = marketing;
        this.providerType = providerType;
        this.push = push;
        this.createdAt = createdAt;
        this.id = id;
        this.updatedAt = updatedAt;
        this.deviceToken = deviceToken;
        this.email = email;
        this.nickname = nickname;
        this.providerId = providerId;
    }

    /**
     * Getter for <code>duty_it.users.auto_add_bookmark_to_calendar</code>.
     */
    public Boolean getAutoAddBookmarkToCalendar() {
        return this.autoAddBookmarkToCalendar;
    }

    /**
     * Setter for <code>duty_it.users.auto_add_bookmark_to_calendar</code>.
     */
    public Users setAutoAddBookmarkToCalendar(Boolean autoAddBookmarkToCalendar) {
        this.autoAddBookmarkToCalendar = autoAddBookmarkToCalendar;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.bookmark</code>.
     */
    public Boolean getBookmark() {
        return this.bookmark;
    }

    /**
     * Setter for <code>duty_it.users.bookmark</code>.
     */
    public Users setBookmark(Boolean bookmark) {
        this.bookmark = bookmark;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.calendar</code>.
     */
    public Boolean getCalendar() {
        return this.calendar;
    }

    /**
     * Setter for <code>duty_it.users.calendar</code>.
     */
    public Users setCalendar(Boolean calendar) {
        this.calendar = calendar;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.marketing</code>.
     */
    public Boolean getMarketing() {
        return this.marketing;
    }

    /**
     * Setter for <code>duty_it.users.marketing</code>.
     */
    public Users setMarketing(Boolean marketing) {
        this.marketing = marketing;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.provider_type</code>.
     */
    public Byte getProviderType() {
        return this.providerType;
    }

    /**
     * Setter for <code>duty_it.users.provider_type</code>.
     */
    public Users setProviderType(Byte providerType) {
        this.providerType = providerType;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.push</code>.
     */
    public Boolean getPush() {
        return this.push;
    }

    /**
     * Setter for <code>duty_it.users.push</code>.
     */
    public Users setPush(Boolean push) {
        this.push = push;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>duty_it.users.created_at</code>.
     */
    public Users setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>duty_it.users.id</code>.
     */
    public Users setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>duty_it.users.updated_at</code>.
     */
    public Users setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.device_token</code>.
     */
    public String getDeviceToken() {
        return this.deviceToken;
    }

    /**
     * Setter for <code>duty_it.users.device_token</code>.
     */
    public Users setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>duty_it.users.email</code>.
     */
    public Users setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.nickname</code>.
     */
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Setter for <code>duty_it.users.nickname</code>.
     */
    public Users setNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * Getter for <code>duty_it.users.provider_id</code>.
     */
    public String getProviderId() {
        return this.providerId;
    }

    /**
     * Setter for <code>duty_it.users.provider_id</code>.
     */
    public Users setProviderId(String providerId) {
        this.providerId = providerId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.autoAddBookmarkToCalendar == null) {
            if (other.autoAddBookmarkToCalendar != null)
                return false;
        }
        else if (!this.autoAddBookmarkToCalendar.equals(other.autoAddBookmarkToCalendar))
            return false;
        if (this.bookmark == null) {
            if (other.bookmark != null)
                return false;
        }
        else if (!this.bookmark.equals(other.bookmark))
            return false;
        if (this.calendar == null) {
            if (other.calendar != null)
                return false;
        }
        else if (!this.calendar.equals(other.calendar))
            return false;
        if (this.marketing == null) {
            if (other.marketing != null)
                return false;
        }
        else if (!this.marketing.equals(other.marketing))
            return false;
        if (this.providerType == null) {
            if (other.providerType != null)
                return false;
        }
        else if (!this.providerType.equals(other.providerType))
            return false;
        if (this.push == null) {
            if (other.push != null)
                return false;
        }
        else if (!this.push.equals(other.push))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.deviceToken == null) {
            if (other.deviceToken != null)
                return false;
        }
        else if (!this.deviceToken.equals(other.deviceToken))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.nickname == null) {
            if (other.nickname != null)
                return false;
        }
        else if (!this.nickname.equals(other.nickname))
            return false;
        if (this.providerId == null) {
            if (other.providerId != null)
                return false;
        }
        else if (!this.providerId.equals(other.providerId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.autoAddBookmarkToCalendar == null) ? 0 : this.autoAddBookmarkToCalendar.hashCode());
        result = prime * result + ((this.bookmark == null) ? 0 : this.bookmark.hashCode());
        result = prime * result + ((this.calendar == null) ? 0 : this.calendar.hashCode());
        result = prime * result + ((this.marketing == null) ? 0 : this.marketing.hashCode());
        result = prime * result + ((this.providerType == null) ? 0 : this.providerType.hashCode());
        result = prime * result + ((this.push == null) ? 0 : this.push.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.deviceToken == null) ? 0 : this.deviceToken.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.nickname == null) ? 0 : this.nickname.hashCode());
        result = prime * result + ((this.providerId == null) ? 0 : this.providerId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(autoAddBookmarkToCalendar);
        sb.append(", ").append(bookmark);
        sb.append(", ").append(calendar);
        sb.append(", ").append(marketing);
        sb.append(", ").append(providerType);
        sb.append(", ").append(push);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(id);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(deviceToken);
        sb.append(", ").append(email);
        sb.append(", ").append(nickname);
        sb.append(", ").append(providerId);

        sb.append(")");
        return sb.toString();
    }
}
