/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.DutyIt;
import jooq.Keys;
import jooq.enums.EventsEventType;
import jooq.tables.Bookmarks.BookmarksPath;
import jooq.tables.Hosts.HostsPath;
import jooq.tables.Views.ViewsPath;
import jooq.tables.records.EventsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events extends TableImpl<EventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>duty_it.events</code>
     */
    public static final Events EVENTS = new Events();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventsRecord> getRecordType() {
        return EventsRecord.class;
    }

    /**
     * The column <code>duty_it.events.end_at</code>.
     */
    public final TableField<EventsRecord, LocalDate> END_AT = createField(DSL.name("end_at"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>duty_it.events.is_approved</code>.
     */
    public final TableField<EventsRecord, Boolean> IS_APPROVED = createField(DSL.name("is_approved"), SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>duty_it.events.start_at</code>.
     */
    public final TableField<EventsRecord, LocalDate> START_AT = createField(DSL.name("start_at"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>duty_it.events.host_id</code>.
     */
    public final TableField<EventsRecord, Long> HOST_ID = createField(DSL.name("host_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>duty_it.events.id</code>.
     */
    public final TableField<EventsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>duty_it.events.recruitment_end_at</code>.
     */
    public final TableField<EventsRecord, LocalDateTime> RECRUITMENT_END_AT = createField(DSL.name("recruitment_end_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>duty_it.events.recruitment_start_at</code>.
     */
    public final TableField<EventsRecord, LocalDateTime> RECRUITMENT_START_AT = createField(DSL.name("recruitment_start_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>duty_it.events.thumbnail</code>.
     */
    public final TableField<EventsRecord, String> THUMBNAIL = createField(DSL.name("thumbnail"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>duty_it.events.title</code>.
     */
    public final TableField<EventsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>duty_it.events.uri</code>.
     */
    public final TableField<EventsRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>duty_it.events.event_type</code>.
     */
    public final TableField<EventsRecord, EventsEventType> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(10).asEnumDataType(EventsEventType.class), this, "");

    /**
     * The column <code>duty_it.events.created_at</code>.
     */
    public final TableField<EventsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>duty_it.events.updated_at</code>.
     */
    public final TableField<EventsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private Events(Name alias, Table<EventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Events(Name alias, Table<EventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>duty_it.events</code> table reference
     */
    public Events(String alias) {
        this(DSL.name(alias), EVENTS);
    }

    /**
     * Create an aliased <code>duty_it.events</code> table reference
     */
    public Events(Name alias) {
        this(alias, EVENTS);
    }

    /**
     * Create a <code>duty_it.events</code> table reference
     */
    public Events() {
        this(DSL.name("events"), null);
    }

    public <O extends Record> Events(Table<O> path, ForeignKey<O, EventsRecord> childPath, InverseForeignKey<O, EventsRecord> parentPath) {
        super(path, childPath, parentPath, EVENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EventsPath extends Events implements Path<EventsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EventsPath(Table<O> path, ForeignKey<O, EventsRecord> childPath, InverseForeignKey<O, EventsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EventsPath(Name alias, Table<EventsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EventsPath as(String alias) {
            return new EventsPath(DSL.name(alias), this);
        }

        @Override
        public EventsPath as(Name alias) {
            return new EventsPath(alias, this);
        }

        @Override
        public EventsPath as(Table<?> alias) {
            return new EventsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DutyIt.DUTY_IT;
    }

    @Override
    public Identity<EventsRecord, Long> getIdentity() {
        return (Identity<EventsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EventsRecord> getPrimaryKey() {
        return Keys.KEY_EVENTS_PRIMARY;
    }

    @Override
    public List<ForeignKey<EventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKDQKIYKJ89A9GDFH6CEPO057O6);
    }

    private transient HostsPath _hosts;

    /**
     * Get the implicit join path to the <code>duty_it.hosts</code> table.
     */
    public HostsPath hosts() {
        if (_hosts == null)
            _hosts = new HostsPath(this, Keys.FKDQKIYKJ89A9GDFH6CEPO057O6, null);

        return _hosts;
    }

    private transient BookmarksPath _bookmarks;

    /**
     * Get the implicit to-many join path to the <code>duty_it.bookmarks</code>
     * table
     */
    public BookmarksPath bookmarks() {
        if (_bookmarks == null)
            _bookmarks = new BookmarksPath(this, null, Keys.FK5180RCUNAOGKV8WGJ4EGF55XD.getInverseKey());

        return _bookmarks;
    }

    private transient ViewsPath _views;

    /**
     * Get the implicit to-many join path to the <code>duty_it.views</code>
     * table
     */
    public ViewsPath views() {
        if (_views == null)
            _views = new ViewsPath(this, null, Keys.FKBMSLLKMG09PXDBVHTVEW25HU.getInverseKey());

        return _views;
    }

    @Override
    public Events as(String alias) {
        return new Events(DSL.name(alias), this);
    }

    @Override
    public Events as(Name alias) {
        return new Events(alias, this);
    }

    @Override
    public Events as(Table<?> alias) {
        return new Events(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(String name) {
        return new Events(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Name name) {
        return new Events(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Table<?> name) {
        return new Events(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Condition condition) {
        return new Events(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
