/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.DutyIt;
import jooq.Keys;
import jooq.tables.Events.EventsPath;
import jooq.tables.records.HostsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hosts extends TableImpl<HostsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>duty_it.hosts</code>
     */
    public static final Hosts HOSTS = new Hosts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostsRecord> getRecordType() {
        return HostsRecord.class;
    }

    /**
     * The column <code>duty_it.hosts.id</code>.
     */
    public final TableField<HostsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>duty_it.hosts.name</code>.
     */
    public final TableField<HostsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>duty_it.hosts.thumbnail</code>.
     */
    public final TableField<HostsRecord, String> THUMBNAIL = createField(DSL.name("thumbnail"), SQLDataType.VARCHAR(255), this, "");

    private Hosts(Name alias, Table<HostsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Hosts(Name alias, Table<HostsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>duty_it.hosts</code> table reference
     */
    public Hosts(String alias) {
        this(DSL.name(alias), HOSTS);
    }

    /**
     * Create an aliased <code>duty_it.hosts</code> table reference
     */
    public Hosts(Name alias) {
        this(alias, HOSTS);
    }

    /**
     * Create a <code>duty_it.hosts</code> table reference
     */
    public Hosts() {
        this(DSL.name("hosts"), null);
    }

    public <O extends Record> Hosts(Table<O> path, ForeignKey<O, HostsRecord> childPath, InverseForeignKey<O, HostsRecord> parentPath) {
        super(path, childPath, parentPath, HOSTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HostsPath extends Hosts implements Path<HostsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HostsPath(Table<O> path, ForeignKey<O, HostsRecord> childPath, InverseForeignKey<O, HostsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HostsPath(Name alias, Table<HostsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HostsPath as(String alias) {
            return new HostsPath(DSL.name(alias), this);
        }

        @Override
        public HostsPath as(Name alias) {
            return new HostsPath(alias, this);
        }

        @Override
        public HostsPath as(Table<?> alias) {
            return new HostsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DutyIt.DUTY_IT;
    }

    @Override
    public Identity<HostsRecord, Long> getIdentity() {
        return (Identity<HostsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<HostsRecord> getPrimaryKey() {
        return Keys.KEY_HOSTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<HostsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_HOSTS_UK9G0HG6HKNG2B8HTBSNMJTPMG3);
    }

    private transient EventsPath _events;

    /**
     * Get the implicit to-many join path to the <code>duty_it.events</code>
     * table
     */
    public EventsPath events() {
        if (_events == null)
            _events = new EventsPath(this, null, Keys.FKDQKIYKJ89A9GDFH6CEPO057O6.getInverseKey());

        return _events;
    }

    @Override
    public Hosts as(String alias) {
        return new Hosts(DSL.name(alias), this);
    }

    @Override
    public Hosts as(Name alias) {
        return new Hosts(alias, this);
    }

    @Override
    public Hosts as(Table<?> alias) {
        return new Hosts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hosts rename(String name) {
        return new Hosts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hosts rename(Name name) {
        return new Hosts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hosts rename(Table<?> name) {
        return new Hosts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hosts where(Condition condition) {
        return new Hosts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hosts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hosts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hosts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hosts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hosts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hosts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hosts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hosts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hosts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
