/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.Hosts;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostsRecord extends UpdatableRecordImpl<HostsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>duty_it.hosts.id</code>.
     */
    public HostsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.hosts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>duty_it.hosts.name</code>.
     */
    public HostsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.hosts.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>duty_it.hosts.thumbnail</code>.
     */
    public HostsRecord setThumbnail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.hosts.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HostsRecord
     */
    public HostsRecord() {
        super(Hosts.HOSTS);
    }

    /**
     * Create a detached, initialised HostsRecord
     */
    public HostsRecord(Long id, String name, String thumbnail) {
        super(Hosts.HOSTS);

        setId(id);
        setName(name);
        setThumbnail(thumbnail);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised HostsRecord
     */
    public HostsRecord(jooq.tables.pojos.Hosts value) {
        super(Hosts.HOSTS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setThumbnail(value.getThumbnail());
            resetChangedOnNotNull();
        }
    }
}
