/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDateTime;

import jooq.tables.Users;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>duty_it.users.auto_add_bookmark_to_calendar</code>.
     */
    public UsersRecord setAutoAddBookmarkToCalendar(Boolean value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.auto_add_bookmark_to_calendar</code>.
     */
    public Boolean getAutoAddBookmarkToCalendar() {
        return (Boolean) get(0);
    }

    /**
     * Setter for <code>duty_it.users.bookmark</code>.
     */
    public UsersRecord setBookmark(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.bookmark</code>.
     */
    public Boolean getBookmark() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>duty_it.users.calendar</code>.
     */
    public UsersRecord setCalendar(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.calendar</code>.
     */
    public Boolean getCalendar() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>duty_it.users.marketing</code>.
     */
    public UsersRecord setMarketing(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.marketing</code>.
     */
    public Boolean getMarketing() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>duty_it.users.provider_type</code>.
     */
    public UsersRecord setProviderType(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.provider_type</code>.
     */
    public Byte getProviderType() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>duty_it.users.push</code>.
     */
    public UsersRecord setPush(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.push</code>.
     */
    public Boolean getPush() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>duty_it.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>duty_it.users.id</code>.
     */
    public UsersRecord setId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.id</code>.
     */
    public Long getId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>duty_it.users.updated_at</code>.
     */
    public UsersRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>duty_it.users.device_token</code>.
     */
    public UsersRecord setDeviceToken(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.device_token</code>.
     */
    public String getDeviceToken() {
        return (String) get(9);
    }

    /**
     * Setter for <code>duty_it.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.email</code>.
     */
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>duty_it.users.nickname</code>.
     */
    public UsersRecord setNickname(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.nickname</code>.
     */
    public String getNickname() {
        return (String) get(11);
    }

    /**
     * Setter for <code>duty_it.users.provider_id</code>.
     */
    public UsersRecord setProviderId(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>duty_it.users.provider_id</code>.
     */
    public String getProviderId() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Boolean autoAddBookmarkToCalendar, Boolean bookmark, Boolean calendar, Boolean marketing, Byte providerType, Boolean push, LocalDateTime createdAt, Long id, LocalDateTime updatedAt, String deviceToken, String email, String nickname, String providerId) {
        super(Users.USERS);

        setAutoAddBookmarkToCalendar(autoAddBookmarkToCalendar);
        setBookmark(bookmark);
        setCalendar(calendar);
        setMarketing(marketing);
        setProviderType(providerType);
        setPush(push);
        setCreatedAt(createdAt);
        setId(id);
        setUpdatedAt(updatedAt);
        setDeviceToken(deviceToken);
        setEmail(email);
        setNickname(nickname);
        setProviderId(providerId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(jooq.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setAutoAddBookmarkToCalendar(value.getAutoAddBookmarkToCalendar());
            setBookmark(value.getBookmark());
            setCalendar(value.getCalendar());
            setMarketing(value.getMarketing());
            setProviderType(value.getProviderType());
            setPush(value.getPush());
            setCreatedAt(value.getCreatedAt());
            setId(value.getId());
            setUpdatedAt(value.getUpdatedAt());
            setDeviceToken(value.getDeviceToken());
            setEmail(value.getEmail());
            setNickname(value.getNickname());
            setProviderId(value.getProviderId());
            resetChangedOnNotNull();
        }
    }
}
